version: "3.9"

services:
  barber-shop-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/barber-shop-ui
      - /barber-shop-ui/node_modules
    command: ng serve --host 0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - barber-shop-net

networks:
  barber-shop-net:
    name: barber-shop-net
