version: "3.8"

services:
  mockServer:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_ENABLE_CORS_FOR_API: "true"
      MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES: "true"
      MOCKSERVER_CORS_ALLOW_ORIGIN: "*"
      MOCKSERVER_CORS_ALLOW_METHODS: "CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE"
      MOCKSERVER_CORS_ALLOW_HEADERS: "*"
      MOCKSERVER_CORS_ALLOW_CREDENTIALS: "true"
      MOCKSERVER_CORS_MAX_AGE_IN_SECONDS: "3600"
    volumes:
      - ./initializerJson.json:/config/initializerJson.json
